"use client";

import * as React from "react";
import { Activity, Calculator } from "lucide-react";
import { toast } from "sonner";
import { CartesianGrid, Line, ReferenceLine, ResponsiveContainer, Scatter, ScatterChart, Tooltip, XAxis, YAxis } from "recharts";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import type { ArbitrationRecord, GradeRecord, GradingQuestion } from "./types";

export function ReliabilityTab({ questions, grades, arbitrations }: { questions: GradingQuestion[]; grades: GradeRecord[]; arbitrations: ArbitrationRecord[] }) {
  const [data, setData] = React.useState<any>(null);
  const [calibrated, setCalibrated] = React.useState(false);
  const courseId = questions[0]?.course_id;
  const points = grades.filter((item) => item.is_ai).flatMap((grade) => { const arbitration = arbitrations.find((item) => item.script_id === grade.script_id && item.final_score != null); return arbitration ? [{ ai: Number(grade.score), human: Number(arbitration.final_score) }] : []; });
  async function compute() { if (!courseId) return; const response = await fetch(`/api/grading/reliability?course_id=${courseId}`, { method: "POST" }); const result = await response.json(); if (!response.ok) return toast.error(result.error); setData(result); toast.success("Reliability metrics refreshed"); }
  return <div className="space-y-6"><div className="flex justify-end"><Button onClick={compute} disabled={!courseId}><Calculator className="mr-2 h-4 w-4" />Compute reliability</Button></div>
    <div className="grid gap-4 sm:grid-cols-3">{[{ label: "Cohen's κ", value: data?.metrics ? Number(data.metrics.kappa).toFixed(2) : "—", note: "Agreement beyond chance" }, { label: "Mean absolute difference", value: data?.metrics ? Number(data.metrics.mad).toFixed(2) : "—", note: "Average marks apart" }, { label: "AI bias", value: data?.metrics ? `${Number(data.metrics.bias) >= 0 ? "+" : ""}${Number(data.metrics.bias).toFixed(2)}` : "—", note: "Positive means AI is lenient" }].map((item) => <Card key={item.label}><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{item.label}</CardTitle></CardHeader><CardContent><div className="flex items-center gap-2"><span className="text-3xl font-semibold tabular-nums">{item.value}</span>{item.label.includes("κ") && data?.metrics && <Badge variant={Number(data.metrics.kappa) >= .85 ? "success" : "warning"}>target ≥ .85</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{item.note}</p></CardContent></Card>)}</div>
    <div className="grid gap-6 lg:grid-cols-[1.4fr_.6fr]"><Card><CardHeader><CardTitle className="text-base">AI vs reconciled human scores</CardTitle></CardHeader><CardContent className="h-72">{points.length ? <ResponsiveContainer width="100%" height="100%"><ScatterChart margin={{ top: 10, right: 10, bottom: 10, left: 0 }}><CartesianGrid strokeDasharray="3 3" /><XAxis type="number" dataKey="ai" name="AI" /><YAxis type="number" dataKey="human" name="Human" /><Tooltip cursor={{ strokeDasharray: "3 3" }} /><ReferenceLine segment={[{ x: 0, y: 0 }, { x: 100, y: 100 }]} stroke="hsl(var(--primary))" strokeDasharray="4 4" /><Scatter data={points} fill="hsl(var(--primary))" /></ScatterChart></ResponsiveContainer> : <div className="flex h-full items-center justify-center text-sm text-muted-foreground">Resolve examiner grades to populate agreement data.</div>}</CardContent></Card><Card><CardHeader><CardTitle className="flex items-center justify-between text-base"><span>Examiner calibration</span>{data?.profiles?.length > 0 && <Button size="sm" variant={calibrated ? "default" : "outline"} onClick={() => setCalibrated((value) => !value)}>{calibrated ? "Calibration on" : "Apply calibration"}</Button>}</CardTitle></CardHeader><CardContent className="space-y-3">{data?.profiles?.length ? data.profiles.map((profile: any) => <div key={profile.id} className="rounded-lg border p-3"><div className="flex items-center justify-between"><span className="text-sm font-medium">Examiner {profile.examiner_id.slice(0, 6)}</span><Badge variant={Number(profile.leniency) > 0 ? "warning" : "secondary"}>{Number(profile.leniency) > 0 ? "Lenient" : "Harsh"}</Badge></div><p className="mt-2 text-xs text-muted-foreground">Average {Number(profile.leniency) >= 0 ? "+" : ""}{Number(profile.leniency).toFixed(1)} marks · n={profile.samples}</p><p className="mt-1 text-xs">{calibrated ? `Preview applies ${Number(profile.calibration_offset).toFixed(1)} marks` : `Suggested offset ${Number(profile.calibration_offset).toFixed(1)}`}</p></div>) : <div className="flex items-center gap-2 text-sm text-muted-foreground"><Activity className="h-4 w-4" />Needs reconciled samples.</div>}</CardContent></Card></div>
  </div>;
}
